### ISSUE TITLE
AttributeError: module 'django.db.models' has no attribute 'model

### ISSUE THREAD

**Issue by LinuxNetHub** [mcdavidsh/Jasmin-Web-Panel-V2#10]
Traceback (most recent call last):
  File "manage.py", line 22, in <module>
    main()
  File "manage.py", line 18, in main
    execute_from_command_line(sys.argv)
  File "/home/rana/Desktop/myweb/myvenv/lib/python3.8/site-packages/django/core/management/__init__.py", line 419, in execute_from_command_line
    utility.execute()
  File "/home/rana/Desktop/myweb/myvenv/lib/python3.8/site-packages/django/core/management/__init__.py", line 395, in execute
    django.setup()
  File "/home/rana/Desktop/myweb/myvenv/lib/python3.8/site-packages/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/home/rana/Desktop/myweb/myvenv/lib/python3.8/site-packages/django/apps/registry.py", line 114, in populate
    app_config.import_models()
  File "/home/rana/Desktop/myweb/myvenv/lib/python3.8/site-packages/django/apps/config.py", line 301, in import_models
    self.models_module = import_module(models_module_name)
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/rana/Desktop/myweb/myproject/main/models.py", line 7, in <module>
    class Main(models.model):
AttributeError: module 'django.db.models' has no attribute 'model'

**Comment by LinuxNetHub** [comment]
![Uploading Screenshot from 2021-04-14 23-50-50.png…]()
